### ISSUE TITLE
Deferred benchmark slow by default

### ISSUE THREAD

**Issue by psorowka** [bestiejs/benchmark.js#111]
We are trying to apply benchmarks to an asynchronous function but the `deferred` option causes us some headaches. We observed that setting `deferred: true` slows down the benchmarks *enormously* by default.

Here is a minimal example to outline what I am referring to:

```
var suite = new (require('benchmark').Suite)();

suite
  .add('NOOP but deferred true',
  {
    defer: true,
    fn: function(deferred) {

      return deferred.resolve();
    }
  })
  .add('NOOP but deferred false',
  {
    defer: false,
    fn: function() {

      return true;
    }
  })
  .on('cycle', function(event) {

    console.log(String(event.target));
  })
  .run({async: false});
```

The result on a recent MacbookPro is:

```
$ node index.js 
NOOP but deferred true x 736 ops/sec ±1.50% (12 runs sampled)
NOOP but deferred false x 105,710,820 ops/sec ±0.95% (92 runs sampled)
````
Setting `async: true` does not change anything.

Expected result was that the deferred NOOP function should be basically exactly as fast as the other. Do I miss something or is that a bug?

**Comment by jdalton** [comment]
Hi @psorowka! This should be resolved in the edge master branch.

**Comment by psorowka** [comment]
Hi @jdalton thanks for the quick reply. I indeed did work on 1.0.0. Tried it on v2.0.0-pre now and see an improvement but still not what I expected:

```
$ node index.js
NOOP but deferred true x 421,970 ops/sec ±15.10% (41 runs sampled)
NOOP but deferred false x 99,471,659 ops/sec ±3.22% (81 runs sampled)
```

**Comment by jdalton** [comment]
I'm sorry the microbenchmark did not perform to your expectations, but that is the nature of a microbenchmark.

**Comment by psorowka** [comment]
my only expectation was that setting `deferred: true` should not make the benchmark 250 times slower. What's wrong about this assumption?

**Comment by jdalton** [comment]
Engine do lots of optimizations under the hood. Microbenchmarks are especially bad because you may think it's straight forward and that things should be have a certain way but because of these optimizations two completely different scenarios are being run.

**Comment by psorowka** [comment]
okay then maybe I turn my question around: 

I was testing an async function and seeing quite bad results when using the `deferred` option. I then wanted to see the maximum gainable performance if my code would be perfectly fast, this is why I put this scenario in place.

Do I interprete these results and your comment correctly, that setting `deferred: true` is not recommended usage when testing very fast operations?

**Comment by jdalton** [comment]
> Do I interprete these results and your comment correctly, that setting deferred: true is not recommended usage when testing very fast operations?

No, deferred is fine. It's intended for things like promises. Or any other case where the function/bench does not complete immediately.

**Comment by anonghuser** [comment]
A note for people stumbling on this in the future: If you resolve the deferred object synchronously, the performance is somehow much slower than if you resolve it asynchronously, i.e. via a promise or microtask or process.nextTick.

```
const suite = Benchmark.Suite()
suite.add('sync', {
    fn() {}
})
suite.add('defer inline', {
    defer:true,
    fn(deferred) {
        deferred.resolve()
    }
})
suite.add('defer promise', {
    defer:true,
    fn(deferred) {
        Promise.resolve().then(()=>deferred.resolve())
    }
})
suite.add('defer nextTick', {
    defer:true,
    fn(deferred) {
        process.nextTick(()=>deferred.resolve())
    }
})
suite.add('defer queueMicrotask', {
    defer:true,
    fn(deferred) {
        queueMicrotask(()=>deferred.resolve())
    }
})
suite.add('defer setImmediate', {
    defer:true,
    fn(deferred) {
        setImmediate(()=>deferred.resolve())
    }
})
suite.add('defer setTimeout 0', {
    defer:true,
    fn(deferred) {
        setTimeout(()=>deferred.resolve(),0)
    }
})
suite.on('cycle', e=>console.log(e.target+''))
suite.run()
```

Result on one machine I tried it on:
```
sync x 296,433,321 ops/sec ±9.63% (40 runs sampled)
defer inline x 19,351 ops/sec ±58.58% (10 runs sampled)
defer promise x 2,492,267 ops/sec ±17.43% (45 runs sampled)
defer nextTick x 875,521 ops/sec ±57.09% (46 runs sampled)
defer queueMicrotask x 796,579 ops/sec ±34.70% (43 runs sampled)
defer setImmediate x 125,719 ops/sec ±11.36% (39 runs sampled)
defer setTimeout 0 x 601 ops/sec ±15.84% (64 runs sampled)
```
Differences between sync and `defer:true` are expected. Differences between promise, microtask or process.nextTick are slightly surprising since the three concepts are very similar, but ultimately it's up to the engine so whatever. But the inline resolve being orders of magnitude slower than the async resolve versions seemed very surprising.

By chance I also tried inline resolve in async function without await. 
```
suite.add('should be same as "defer inline" but gives me stack overflow', {
    defer:true,
    async fn(deferred) {
        deferred.resolve()
    }
})
```
It threw stack overflow error, which pointed me to find that when using `defer:true` the iterations are done recursively. I don't know if that explains why it'd be slower, but it adds a reason to not use synchronous `resolve()` even if its performance were ok. 

I'm still curious if someone can explain the performance aspect, but for the people just looking for solution instead of explanation - just change the resolve to be async.
